In [1]:
import warnings
warnings.filterwarnings("ignore")

#### EDA and Encoding

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import sklearn

In [3]:
df = pd.read_csv("G:\\DS150423\\MACHINE LEARNING\\train_set.csv")
df.head()

Year  OGC                                       OG   DC               Dept  \
0  2015    4                         Community Health  DPH      Public Health   
1  2013    4                         Community Health  DPH      Public Health   
2  2015    6         General Administration & Finance  ASR  Assessor/Recorder   
3  2016    1                        Public Protection  POL             Police   
4  2013    2  Public Works, Transportation & Commerce  HHP   PUC Hetch Hetchy   

    UC                                            Union  \
0  250                SEIU - Health Workers, Local 1021   
1   39                   Stationary Engineers, Local 39   
2   21  Prof & Tech Engineers - Miscellaneous, Local 21   
3  911                     Police Officers' Association   
4   21  Prof & Tech Engineers - Miscellaneous, Local 21   

                        JF                             Job     EI  Salaries  \
0  Med Therapy & Auxiliary                Morgue Attendant   6725     12196   
1         Journeyman Trade             Stationary Engineer  25058     74639   
2     Appraisal & Taxation  Senior Real Property Appraiser  46108    100554   
3          Police Services                      Sergeant 3  33369    140164   
4      Information Systems             IS Engineer-Journey  28684     58813   

   Overtime       H/D        YT  Total_Compensation  
0         0      0.00  Calendar               16158  
1      2820  12703.31    Fiscal              115784  
2         0  12424.50  Calendar              144708  
3     52754  13043.87    Fiscal              242323  
4         0   7655.28  Calendar               82106

In [4]:
df.shape

(287836, 15)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287836 entries, 0 to 287835
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Year                287836 non-null  int64  
 1   OGC                 287836 non-null  int64  
 2   OG                  287836 non-null  object 
 3   DC                  287836 non-null  object 
 4   Dept                287836 non-null  object 
 5   UC                  287836 non-null  int64  
 6   Union               287800 non-null  object 
 7   JF                  287798 non-null  object 
 8   Job                 287836 non-null  object 
 9   EI                  287836 non-null  int64  
 10  Salaries            287836 non-null  int64  
 11  Overtime            287836 non-null  int64  
 12  H/D                 287836 non-null  float64
 13  YT                  287836 non-null  object 
 14  Total_Compensation  287836 non-null  int64  
dtypes: float64(1), int64(7), object(7)

In [6]:
df.describe()

Year            OGC             UC             EI  \
count  287836.000000  287836.000000  287836.000000  287836.000000   
mean     2014.250104       2.976007     490.540186   26913.060020   
std         1.016282       1.575586     333.238723   15539.719696   
min      2013.000000       1.000000       1.000000       1.000000   
25%      2013.000000       2.000000     236.000000   13434.000000   
50%      2014.000000       2.000000     535.000000   27013.000000   
75%      2015.000000       4.000000     790.000000   40397.250000   
max      2016.000000       7.000000     990.000000   53794.000000   

            Salaries       Overtime            H/D  Total_Compensation  
count  287836.000000  287836.000000  287836.000000       287836.000000  
mean    63262.713139    4401.037115    8932.876472        97990.329882  
std     44638.657748   11079.137749    4894.072024        67750.020573  
min    -68771.000000  -12308.000000   -2940.470000       -74082.000000  
25%     23406.000000       0.000000    4358.347500        35977.000000  
50%     62504.500000       0.000000   11982.035000        98033.000000  
75%     93000.250000    2738.000000   12801.790000       142138.250000  
max    515101.000000  227313.000000   21872.800000       653498.000000

In [7]:
df.columns

Index(['Year', 'OGC', 'OG', 'DC', 'Dept', 'UC', 'Union', 'JF', 'Job', 'EI',
       'Salaries', 'Overtime', 'H/D', 'YT', 'Total_Compensation'],
      dtype='object')

In [8]:
df.isnull().sum()

Year                   0
OGC                    0
OG                     0
DC                     0
Dept                   0
UC                     0
Union                 36
JF                    38
Job                    0
EI                     0
Salaries               0
Overtime               0
H/D                    0
YT                     0
Total_Compensation     0
dtype: int64

In [9]:
df.dropna(inplace=True)
df.isnull().sum()

Year                  0
OGC                   0
OG                    0
DC                    0
Dept                  0
UC                    0
Union                 0
JF                    0
Job                   0
EI                    0
Salaries              0
Overtime              0
H/D                   0
YT                    0
Total_Compensation    0
dtype: int64

In [10]:
le = LabelEncoder()

df['OG'] = le.fit_transform(df['OG'])
df['DC'] = le.fit_transform(df['DC'])
df['Dept'] = le.fit_transform(df['Dept'])
df['Union'] = le.fit_transform(df['Union'])
df['JF'] = le.fit_transform(df['JF'])
df['Job'] = le.fit_transform(df['Job'])
df['YT'] = le.fit_transform(df['YT'])

In [11]:
df['Year'] = le.fit_transform(df['Year'])

In [12]:
df.head()

Year  OGC  OG  DC  Dept   UC  Union  JF   Job     EI  Salaries  Overtime  \
0     2    4   0  19    45  250     56  28   670   6725     12196         0   
1     0    4   0  19    45   39     62  23  1009  25058     74639      2820   
2     2    6   2   5     5   21     51   6   909  46108    100554         0   
3     3    1   5  39    42  911     46  35   923  33369    140164     52754   
4     0    2   6  28    38   21     51  22   496  28684     58813         0   

        H/D  YT  Total_Compensation  
0      0.00   0               16158  
1  12703.31   1              115784  
2  12424.50   0              144708  
3  13043.87   1              242323  
4   7655.28   0               82106

In [13]:
X = df[df.columns.drop('Total_Compensation')]
Y = df['Total_Compensation']

#### Data Modeling and Training

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [16]:
model = LinearRegression()

model.fit(X_train, Y_train)

LinearRegression()

In [17]:
predictions = model.predict(X_test)
predictions

array([241732.45891796, 155867.79933136, 119242.32490051, ...,
       239466.78145231, 226041.74682728, 117382.942753  ])

In [18]:
model.intercept_

98025.15391464485

In [19]:
model.coef_

array([ 1.07144069e+02, -8.72328884e+02, -6.03793443e+02, -1.31385884e+02,
        2.78802515e+02,  8.04687790e+01, -1.35115668e+02,  2.15664138e+02,
        1.25559356e+02,  7.09261201e+00,  5.79415309e+04,  1.31424280e+04,
        5.68786142e+03, -2.10286512e+02])

#### Total_Compensation Predicted Values for Employee

In [20]:
y = (8.53434878e+01*X['Year'] + (-8.97064344e+02) *X['OGC'] + (-6.23906143e+02)*X['OG'] + (-1.27705965e+02)*X['DC'] +
        2.70032935e+02*X['Dept'] +  7.62663015e+01*X['UC'] + (-1.37735630e+02)*X['Union'] + 2.16727291e+02*X['JF'] +
        1.22211126e+02*X['Job'] + 2.49096316e+01*X['EI'] + 5.78224258e+04*X['Salaries'] + 1.31122868e+04*X['Overtime'] +
        5.71249091e+03*X['H/D'] + (-2.08157162e+02)*X['YT'])       
y

0         7.054754e+08
1         4.426105e+09
2         5.886501e+09
3         8.871878e+09
4         3.445217e+09
              ...     
287831    5.036732e+09
287832    1.806751e+09
287833    6.115193e+09
287834    8.580740e+08
287835    6.267276e+09
Length: 287798, dtype: float64

#### Mean Total_Compensation for Employee

In [21]:
y.mean()

3767891224.311433

In [22]:
y.describe()

count    2.877980e+05
mean     3.767891e+09
std      2.646075e+09
min     -3.976040e+09
25%      1.393000e+09
50%      3.732998e+09
75%      5.525864e+09
max      2.985919e+10
dtype: float64

#### Cross-Validation

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val = cross_val_score(model, X_test, Y_test, cv = 10)
cross_val

array([0.98533985, 0.98868755, 0.98590125, 0.98659351, 0.99045484,
       0.98938448, 0.98544834, 0.98572041, 0.98787314, 0.98659032])

In [25]:
mean_score = np.mean(cross_val)
mean_score

0.9871993680504954

#### Mean accuracy of model = 98.8%